### ISSUE TITLE
Projects crash with no `default` environment, even if that environment is not indicated

### ISSUE THREAD

**Issue by hamptonsmith** [hamptonsmith/pelton3#2]
For example, event invoked as `pelton start --config foo`, the project will crash if there is no `default` environment. Additionally, providing an empty `default` is complicated by https://github.com/hamptonsmith/pelton3/issues/1.

```
ConfigError: Requested environment not defined in "environments": default
    at walkDependencies (file:///usr/lib/node_modules/@shieldsbetter/pelton/utils/walk-dependencies.mjs:29:19)
    at inDependencyOrder (file:///usr/lib/node_modules/@shieldsbetter/pelton/utils/in-dependency-order.mjs:8:5)
    at build (file:///usr/lib/node_modules/@shieldsbetter/pelton/steps/build.mjs:11:5)
    at buildStep (file:///usr/lib/node_modules/@shieldsbetter/pelton/pelton-lib.mjs:149:12)
    at manifestStep (file:///usr/lib/node_modules/@shieldsbetter/pelton/pelton-lib.mjs:159:30)
    at Array.commandLevel.start (file:///usr/lib/node_modules/@shieldsbetter/pelton/pelton-lib.mjs:138:25)
    at commandLevel (file:///usr/lib/node_modules/@shieldsbetter/pelton/utils/command-level.mjs:58:17)
    at pelton (file:///usr/lib/node_modules/@shieldsbetter/pelton/pelton-lib.mjs:87:5)
```

**Comment by hamptonsmith** [comment]
Test comment
